version: "3.3"

services:
  web:
    container_name: spring.testapp.application
    build: .
    expose:
      - "8080"
    env_file: .env
    depends_on:
      - mysql
    networks:
      local_network:
        ipv4_address: 172.28.1.4

  mysql:
    image: mysql:latest
    container_name: spring.testapp.mysql
    volumes:
      - db_data:/var/lib/mysql:rw
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      local_network:
        ipv4_address: ${DB_HOST}
    env_file: .env

volumes:
  db_data:

networks:
  local_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
